const showcaseRecipeImages: Record<string, string> = {
  'Abacate com banana e aveia': '/images/recipes/abacate-com-banana-e-aveia.webp',
  'Abacate com manga': '/images/recipes/abacate-com-manga.webp',
  'Arroz com lentilha e abóbora': '/images/recipes/arroz-com-lentilha-e-abobora.webp',
  'Arroz com lentilha e cenoura': '/images/recipes/arroz-com-lentilha-e-cenoura.webp',
  'Aveia cremosa com manga': '/images/recipes/aveia-cremosa-com-manga.webp',
  'Banana com abacate': '/images/recipes/banana-com-abacate.webp',
  'Batata-doce amassada com ovo': '/images/recipes/batata-doce-amassada-com-ovo.webp',
  'Bolinho macio de banana e aveia': '/images/recipes/bolinho-macio-de-banana-e-aveia.webp',
  'Carne com abóbora e arroz': '/images/recipes/carne-com-abobora-e-arroz.webp',
  'Carne com arroz e abobrinha': '/images/recipes/carne-com-arroz-e-abobrinha.webp',
  'Carne com batata e beterraba': '/images/recipes/carne-com-batata-e-beterraba.webp',
  'Carne com mandioca e abóbora': '/images/recipes/carne-com-mandioca-e-abobora.webp',
  'Carne com polenta e espinafre': '/images/recipes/carne-com-polenta-e-espinafre.webp',
  'Creme de abóbora com arroz': '/images/recipes/creme-de-abobora-com-arroz.webp',
  'Creme de abóbora com aveia': '/images/recipes/creme-de-abobora-com-aveia.webp',
  'Creme de maçã com aveia': '/images/recipes/creme-de-maca-com-aveia.webp',
  'Creme de mamão com banana': '/images/recipes/creme-de-mamao-com-banana.webp',
  'Creme espesso de ervilha e batata-doce': '/images/recipes/creme-espesso-de-ervilha-e-batata-doce.webp',
  'Cuscuz macio com abacate': '/images/recipes/cuscuz-macio-com-abacate.webp',
  'Cuscuz macio com banana': '/images/recipes/cuscuz-macio-com-banana.webp',
  'Cuscuz macio com ovo': '/images/recipes/cuscuz-macio-com-ovo.webp',
  'Feijão com abóbora e arroz': '/images/recipes/feijao-com-abobora-e-arroz.webp',
  'Feijão com cenoura e arroz': '/images/recipes/feijao-com-cenoura-e-arroz.webp',
  'Feijão com mandioca e brócolis': '/images/recipes/feijao-com-mandioca-e-brocolis.webp',
  'Frango com arroz e brócolis': '/images/recipes/frango-com-arroz-e-brocolis.webp',
  'Frango com batata e cenoura': '/images/recipes/frango-com-batata-e-cenoura.webp',
  'Frango com batata-doce e couve': '/images/recipes/frango-com-batata-doce-e-couve.webp',
  'Frango com mandioca': '/images/recipes/frango-com-mandioca.webp',
  'Frango com polenta e abobrinha': '/images/recipes/frango-com-polenta-e-abobrinha.webp',
  'Frango com quinoa e abobrinha': '/images/recipes/frango-com-quinoa-e-abobrinha.webp',
  'Grão-de-bico com abóbora e arroz': '/images/recipes/grao-de-bico-com-abobora-e-arroz.webp',
  'Grão-de-bico com brócolis': '/images/recipes/grao-de-bico-com-brocolis.webp',
  'Grão-de-bico com cenoura e quinoa': '/images/recipes/grao-de-bico-com-cenoura-e-quinoa.webp',
  'Iogurte natural com banana e aveia': '/images/recipes/iogurte-natural-com-banana-e-aveia.webp',
  'Lentilha com arroz e beterraba': '/images/recipes/lentilha-com-arroz-e-beterraba.webp',
  'Lentilha com batata-doce e couve': '/images/recipes/lentilha-com-batata-doce-e-couve.webp',
  'Maçã assada com aveia': '/images/recipes/maca-assada-com-aveia.webp',
  'Maçã com quinoa macia': '/images/recipes/maca-com-quinoa-macia.webp',
  'Maçã cozida com chia': '/images/recipes/maca-cozida-com-chia.webp',
  'Mamão com iogurte natural': '/images/recipes/mamao-com-iogurte-natural.webp',
  'Mamão com aveia macia': '/images/recipes/mamao-com-aveia-macia.webp',
  'Mamão com pêssego': '/images/recipes/mamao-com-pessego.webp',
  'Manga com banana': '/images/recipes/manga-com-banana.webp',
  'Manga com chia hidratada': '/images/recipes/manga-com-chia-hidratada.webp',
  'Melão com banana amassada': '/images/recipes/melao-com-banana-amassada.webp',
  'Melão com mamão': '/images/recipes/melao-com-mamao.webp',
  'Mingau de banana e aveia': '/images/recipes/mingau-de-banana-e-aveia.webp',
  'Omelete de espinafre com batata': '/images/recipes/omelete-de-espinafre-com-batata.webp',
  'Omelete macia de abobrinha': '/images/recipes/omelete-macia-de-abobrinha.webp',
  'Omelete macia de espinafre': '/images/recipes/omelete-macia-de-espinafre.webp',
  'Ovo com batata e brócolis': '/images/recipes/ovo-com-batata-e-brocolis.webp',
  'Panquequinha de abóbora': '/images/recipes/panquequinha-de-abobora.webp',
  'Panquequinha de banana': '/images/recipes/panquequinha-de-banana.webp',
  'Panquequinha de pera': '/images/recipes/panquequinha-de-pera.webp',
  'Pão macio com abacate': '/images/recipes/pao-macio-com-abacate.webp',
  'Peixe com abóbora e quinoa': '/images/recipes/peixe-com-abobora-e-quinoa.webp',
  'Peixe com arroz e cenoura': '/images/recipes/peixe-com-arroz-e-cenoura.webp',
  'Peixe com batata-doce e abobrinha': '/images/recipes/peixe-com-batata-doce-e-abobrinha.webp',
  'Peixe com mandioca e espinafre': '/images/recipes/peixe-com-mandioca-e-espinafre.webp',
  'Pera com abacate': '/images/recipes/pera-com-abacate.webp',
  'Pera com iogurte natural': '/images/recipes/pera-com-iogurte-natural.webp',
  'Pera cozida com chia hidratada': '/images/recipes/pera-cozida-com-chia-hidratada.webp',
  'Peru com arroz e beterraba': '/images/recipes/peru-com-arroz-e-beterraba.webp',
  'Peru com polenta e cenoura': '/images/recipes/peru-com-polenta-e-cenoura.webp',
  'Peru com quinoa e brócolis': '/images/recipes/peru-com-quinoa-e-brocolis.webp',
  'Pêssego cozido com aveia': '/images/recipes/pessego-cozido-com-aveia.webp',
  'Pêssego cozido com banana': '/images/recipes/pessego-cozido-com-banana.webp',
  'Quinoa com legumes macios': '/images/recipes/quinoa-com-legumes-macios.webp',
  'Quinoa cremosa com banana': '/images/recipes/quinoa-cremosa-com-banana.webp',
  'Quinoa cremosa com pera': '/images/recipes/quinoa-cremosa-com-pera.webp',
  'Sopa espessa de lentilha e batata': '/images/recipes/sopa-espessa-de-lentilha-e-batata.webp',
  'Sopa rústica de batata e ervilha': '/images/recipes/sopa-rustica-de-batata-e-ervilha.webp',
}

export function getRecipeImageUrl(name: string, imageUrl: string | null) {
  return imageUrl || showcaseRecipeImages[name] || null
}
